### ISSUE TITLE
To-do list functionality

### ISSUE THREAD

**Issue by hayjer** [hayjer/Todolist-CC#1]
Implement core To-do list behaviour in todolist.js, including:
- [x] Create to-do item
- [x] Update to-do item (requires auth)
- [x] Delete to-do item (requires auth)
- [x] Filter to-do items by words in description/category
